//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursSistemi_I
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public Nullable<byte> CourseLessonID { get; set; }
        public Nullable<byte> CourseTeacherID { get; set; }
        public Nullable<short> CourseStudentID { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
